# ya pkg add terrakok/split-tabs
[mgr]
prepend_keymap = [
    { on = "\\",    run = "plugin split-tabs spl_toggle",     desc = "Split-tabs: toggle split tabs mode" },
    { on = "<Tab>", run = "plugin split-tabs spl_switch_tab", desc = "Split-tabs: switch to the other pane" },
    { on = "P",     run = "plugin split-tabs spl_preview",    desc = "Split-tabs: toggle preview pane" },
]
