font_size 12.0
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
background_opacity 0.85

# BEGIN_KITTY_THEME
# Alien Blood
include current-theme.conf
# END_KITTY_THEME
